services:
  mongodb:
    image: mongo:latest
    container_name: easyshop-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - easyshop-network

  migration:
    image: ishu11/easyshop-migration:latest
    container_name: easyshop-migration
    env_file:
      - .env
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - easyshop-network

  app:
    image: ishu11/easyshop:latest
    container_name: easyshop
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      migration:
        condition: service_completed_successfully
    networks:
      - easyshop-network
    restart: unless-stopped

networks:
  easyshop-network:
    name: easyshop-network

volumes:
  mongodb_data:
    name: mongodb_data
