apiVersion: v1
kind: ConfigMap
metadata:
  name: easyshop-config
  namespace: easyshop
data:
  MONGODB_URI: "mongodb://mongodb-service:27017/easyshop"
  NODE_ENV: "production"
  NEXT_PUBLIC_API_URL: "http://13.53.140.107/api"
  NEXTAUTH_URL: "http://13.53.140.107/"
  NEXTAUTH_SECRET: "VR0gr7+fzObzLD2IgazRkuUXPz6KYouStCzsug70KkM="
  JWT_SECRET: "136dee4595da8ef5d27255e6c83222568c540db0dc71e7f902b7887de7e498c7"
