apiVersion: v1
kind: Secret
metadata:
  name: easyshop-secrets
  namespace: easyshop
type: Opaque
stringData:
  JWT_SECRET: "136dee4595da8ef5d27255e6c83222568c540db0dc71e7f902b7887de7e498c7"
  NEXTAUTH_SECRET: "VR0gr7+fzObzLD2IgazRkuUXPz6KYouStCzsug70KkM="
